server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=mycalendar
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
